[tool.ruff]
exclude = [
    ".venv",
]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ["E", "F", "W", "B", "I", "ARG"]
ignore = []

fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"tests_AzApi/**/*.py" = ["ARG001","ARG002"]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
